CREATE USER BDGET_TEST IDENTIFIED BY "SPRING_test.123$"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDGET_TEST QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDGET_TEST;
GRANT "RESOURCE" TO BDGET_TEST;
ALTER USER BDGET_TEST DEFAULT ROLE "RESOURCE";